on:
  push:
    branches:
    - main
    - release/*
  workflow_dispatch:

jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-22.04
    steps:
      - uses:
          actions/setup-node@v4
          with:node-version:'16.15.1'


   
