on:
  push:
    branches:
    - main
    - release/*
  workflow_dispatch:

jobs:
  my_job:
    name: deploy Ubuntu
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '16.15.1'
          
      - name : Mocha
        run: |
          cd src;
          npm install -g mocha;
          npm install

      - name : TEste
        run : mocha src/test/convert.js


      - name: Docker Login
        uses: docker/login-action@v3.2.0
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
          

      - name: Build and push Docker images
        uses: docker/build-push-action@v6.0.1
        with:
            context: ./src
            files: ./src/Dockerfile
            push: true
            tags:
              klingermarinho223/conversao-temperatura:${{github.run_number}}
              klingermarinho223/conversao-temperatura:latest
              
              
              
            
        
          
          


   
